services:
  api:
    container_name: test_api
    environment: 
      - DB_NAME=test_db
      - DB_CONNECTION=mongodb://quizzicalTeam:quizzical1234@db:27017
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: test_db
    volumes:
      - "test_db:/var/lib/mongodb/data"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=quizzicalTeam
      - MONGO_INITDB_DATABASE=test_db
      - MONGO_INITDB_ROOT_PASSWORD=quizzical1234
volumes:
  test_db:
